// <auto-generated />
using GZCTF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GZCTF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251001090000_AddScoreFreezeTime")]
    partial class AddScoreFreezeTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new Snapshot().BuildModel(modelBuilder);
#pragma warning restore 612, 618
        }

        private sealed class Snapshot : AppDbContextModelSnapshot
        {
            public new void BuildModel(ModelBuilder modelBuilder) => base.BuildModel(modelBuilder);
        }
    }
}
